Error: Cannot find input file test_locks_11_true-unreach-call_true-valid-memsafety_false-termination.c (exception Sys_error("test_locks_11_true-unreach-call_true-valid-memsafety_false-termination.c: No such file or directory")
Caught Errormsg.Error while parsing
Fatal error: exception Errormsg.Error
Traceback (most recent call last):
  File "SoLVe.py", line 22, in <module>
    main()
  File "SoLVe.py", line 10, in main
    CFG = c_ut.get_file_CFG(file_name)
  File "/home/zeph/SoLVe/cfg_util.py", line 453, in get_file_CFG
    entry_function = full_func_dict["Main "]
KeyError: 'Main '
/home/zeph/avr/bin/avr: line 277: 145428 Segmentation fault      (core dumped) $p_bin/vwn $OUT_PATH $p_bin > $OUT_PATH/data/vwn.output 2>> >(tee -a $OUT_PATH/avr.err >&2)
/home/zeph/avr/bin/avr: line 286: 145449 Segmentation fault      (core dumped) $p_bin/dpa $OUT_PATH $p_bin > $OUT_PATH/data/dpa.output 2>> >(tee -a $OUT_PATH/avr.err >&2)
	(abstraction: sa+uf)
reach: avr_util.h:186: bool access_file(F&, std::__cxx11::string, bool) [with F = std::basic_ifstream<char>; std::__cxx11::string = std::__cxx11::basic_string<char>]: Assertion `0' failed.
/home/zeph/avr/bin/avr: line 295: 145461 Aborted                 (core dumped) $p_bin/reach $OUT_PATH $p_bin > $OUT_PATH/data/reach.output 2>> >(tee -a $OUT_PATH/avr.err >&2)
Could not access file: output/work_test/data/wn.dump

0.08user 0.10system 0:01.24elapsed 14%CPU (0avgtext+0avgdata 10796maxresident)k
93440inputs+472outputs (28major+15917minor)pagefaults 0swaps
